#!/bin/bash

set -e  # Exit on any error
set -u  # Treat unset variables as errors

#LINUX_BIN_FILE="QMLDemo" -> This is the name of the binary file generated by the build process. It should match the name of the executable created in the build directory. TARGET= in the .pro qt file.

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
echo "Script directory: $SCRIPT_DIR"

LINUX_BIN_FILE="$1"

# Check if required arguments are provided
if [ $# -ne 1 ]; then
    echo "Usage: $0 <Binary file name>"
    echo "Example: $0 QMLDemo"
    echo "This will build the application and create a binary executable named QMLDemo in the build directory."
    exit 1
fi

# Check $QT_PATH environment variable
if [ -z "${QT_PATH:-}" ]; then
    echo "Error: QT_PATH environment variable must be set to the Qt installation folder (e.g., /path/to/Qt-6.5.3-static)."
    exit 1
fi

echo "Starting build process..."

# Clean and create build directory
rm -rf build
mkdir -p build
cd build

# Build the application
echo "Running qmake and make..."
$QT_PATH/bin/qmake ..
make -j$(nproc)

mv $LINUX_BIN_FILE ..

echo "Build completed successfully."
