name: Shared Qt MacOS Build

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout source 
        uses: actions/checkout@v4

      - name: Checkout shared tools
        uses: actions/checkout@v4
        with:
          repository: Bolbe/github-build-tools
          path: build-tools

      - name: Download Qt 6.5.3 Compiler for MacOS
        working-directory: ${{ runner.temp }}
        run: |
          curl -L -o Qt653-macos.tar.xz https://github.com/Bolbe/Qt-precompiled/raw/refs/heads/main/macos/Qt653-macos.tar.xz
          tar xf ./Qt653-macos.tar.xz

      - name: Compile project and build package
        working-directory: ${{ github.workspace }}
        env:
          QT_PATH: ${{ runner.temp }}/Qt-6.5.3
        run: zsh ./build-tools/scripts/build-macos.sh ${{ inputs.app_name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.app_name }}-macos
          path: ${{ github.workspace }}/${{ inputs.app_name }}.app.zip
          